ai_locals = [
  ai: 2,
  instructions: 1,
  instructions: 2,
  instructions: 3,
  model: 1,
  model: 2,
  model: 3,
  models: 1,
  router: 1,
  router: 2,
  reasoning: 1,
  reasoning: 2,
  tools: 1,
  action: 1,
  action: 2,
  action: 3,
  action: 4,
  flow: 1,
  flow: 2,
  ash_resource: 1,
  ash_resource: 2,
  mcp_tools: 1,
  browser: 1,
  browser: 2,
  catalog: 1,
  catalog: 2,
  skill: 1,
  load_path: 1,
  subagent: 1,
  subagent: 2,
  handoff: 1,
  handoff: 2,
  controls: 1,
  max_iterations: 1,
  max_model_calls: 1,
  max_tool_calls: 1,
  timeout: 1,
  input: 1,
  input: 2,
  operation: 1,
  operation: 2,
  output: 1,
  output: 2,
  result: 1,
  result: 2,
  steering: 1,
  idle_timeout: 1,
  tool_heartbeat: 1,
  memory: 1,
  observability: 1,
  emit_telemetry: 1,
  emit_signals: 1,
  emit_llm_deltas: 1,
  redact_tool_args: 1,
  stream_content: 1,
  store_content: 1,
  stream_reasoning: 1,
  store_reasoning: 1,
  diagnostics_content: 1,
  metadata: 1
]

[
  line_length: 120,
  import_deps: [:jido, :jido_action],
  locals_without_parens: ai_locals,
  export: [locals_without_parens: ai_locals],
  inputs: ["{mix,.formatter,.credo}.exs", "{config,examples,lib,scripts,test}/**/*.{ex,exs}"]
]
