{application,kagi,
             [{modules,['Elixir.Kagi','Elixir.Kagi.Application',
                        'Elixir.Kagi.Error',
                        'Elixir.Kagi.Error.ConfigurationError',
                        'Elixir.Kagi.Error.InvalidError',
                        'Elixir.Kagi.Error.NotFoundError',
                        'Elixir.Kagi.Error.ServerError','Elixir.Kagi.Filter',
                        'Elixir.Kagi.LogFilter','Elixir.Kagi.Server']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,telemetry,dotenvy,
                             splode]},
              {description,"Easy access to LLM API keys and environment configuration"},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Kagi.Application',[]}}]}.
